### ISSUE TITLE
Slack : l'intégration Reddit et Wikia par RSS semble HS

### ISSUE THREAD

**Issue by Frosty-Z** [dirtylab/wiki#29]
Pourtant ces RSS sont reconnus comme "valides" par Slack.

Essayer de comprendre pourquoi ça ne "passe pas" : format ? données dispo ?

Si nécessaire et pas trop galère, faire une moulinette intermédiaire qui recrache les données au bon format (cf. exemple du Q&A qui fonctionne) et faire pointer l'intégration Slack dessus.

**Comment by sveinburne** [comment]
J'ai résolu l'intégration de reddit grace à IFTT ([If This Then That](https://ifttt.com/connect/reddit/slack)). Dans la mesure où on utilise pas wikia (chez dirtylab), je peux fermer?

**Comment by Frosty-Z** [comment]
Ok parfait ;-)
